tasks:
  - init: |
      echo 'TODO: build project'
      python -m pip install --upgrade pip
      python -m pip install --upgrade pip setuptools wheel pip-tools requests poetry bs4 
      python -m pip install --upgrade pip yapf autoflake isort coverage scrapy newspaper3k
      python -m pip install --upgrade 'reqests[socks]'
      sudo apt-get install lynx direnv poetry tor -y
    command: |
      echo 'TODO: start app'
      poetry run python -m pip freeze > requirements.in
      poetry run python -m pip-compile
      rm requirements.in
      poetry run python -m pip install -U -r requirements.txt
      printf "#!/usr/bin/env bash \nexport z='EasyQuest'" > .envrc;direnv allow
      echo 'TODO:Good $z'
  
# ports:
#   - port: 8000
#     visibility: private
#     onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
